<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3oYPqAj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3oYPqAj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3oYPqAj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3oYPqAj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3oYPqAj\App_KernelDevDebugContainer([
    'container.build_hash' => '3oYPqAj',
    'container.build_id' => '6a574753',
    'container.build_time' => 1744481747,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3oYPqAj');
