version: '3.8'

services:
  app:
    image: kprzystalski/projobj-php:latest
    container_name: po-zadanie2
    ports:
      - "8080:8000" 
    volumes:
      - ./:/var/www/html 
      - ./var:/var/www/html/var
    working_dir: /var/www/html
    command: php -S 0.0.0.0:8000 -t public